# Generated by Django 3.1.7 on 2021-06-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendamount',
            name='is_withdraw',
            field=models.BooleanField(default=True),
        ),
    ]
